### ISSUE TITLE
Wireframe and some details

### ISSUE THREAD

**Issue by dimakm** [dimakm/GWG-shoppingList#1]
**Wireframe with some details**
Here are some information of how we are going to work, what do you think about it? any suggestions are welcome!

**Html:**
The HTML is very simple, only a title and an input with (ADD) button, and we'll put a ul tag so later the list items will be added inside of it.

**CSS:**
Style the input
Style the "Add" button
Style the list items
Style the hide button
having a class to user when clicking an item,it changes background color and strike out text and add a checked mark 

**JAVASCRIPT:**
-Create a new list item when clicking on the "Add" button:
  Store the text of the input field into a var listItem; 
  Append a child to the ul list the child has the listItem var;
  If the input is emplty then an alert shows up to tell the user to put something;
  Add a span with the X button to the list item.

-The X button function:
   when clicking the close X button hide the item.

-Add a "checked" symbol when clicking on a list item 
   add an eventlistener to the li; when clicked then toggle the class that strickes out the item and addes a checked mark.

-Click on the X button to remove a list item
  add event listener to the X; when clicked set the display to none.

**Comment by dimakm** [comment]
@antofon
@Eduardo06sp 
@QAMinn2468

**Comment by dimakm** [comment]
Hello mates, 
@antofon
@Eduardo06sp 
@QAMinn2468
If you like to contribute then can you please add your names to the readme file and send me a pull request ? thank you

**Comment by antofon** [comment]
Should be available after 5pm today, so I will send you the pull request then. But it looks great so far! I suggest checking for duplicates or incrementing the number of a particular item (i.e. 3 apples).

**Comment by QAMinn2468** [comment]
I tried to pull the file, add my name, and push it back and merge it, but it did not seem to work.
Kim (QAMinn2468)

Sent from Mail for Windows 10

**Comment by dimakm** [comment]
@QAMinn2468  I don't know why could this things happen,  I'll try to figure it out. 
I'm so new to GitHub and beginner.

**Comment by dimakm** [comment]
@antofon take your time, I'll be out of town till tomorrow night without my laptop.
Your idea is wonderful, I'll add it .

**Comment by antofon** [comment]
@dimakm ok, I just created a pull request. @QAMinn2468 I believe that @dimakm has to approve our pull requests so they can be merged.

**Comment by Eduardo06sp** [comment]
I made a pull request. I'm a beginner so please be patient with me. :}

**Comment by dimakm** [comment]
Hello everyone, I'm back home!
I accepted the pull requests. glad to be working with you guys.
@QAMinn2468 Kim I added your name to the readme file, can you please make sure the information are correct. 
@Eduardo06sp  don't worry I am a GitHub beginner too ;)

**Comment by QAMinn2468** [comment]
Edits look just right.

Kim

Sent from Mail for Windows 10
